version: "3.9"
services:
  db:
    image: "postgres:14.4"
    restart: always
    container_name: "opub_postgres"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    container_name: "opub_dataset_server"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8005:8000"
    depends_on:
      - db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    restart: always
    container_name: "opub_elasticsearch"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.routing.allocation.disk.watermark.low=97%
      - cluster.routing.allocation.disk.watermark.high=98%
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports: 
      - "9200:9200"
      - "9300:9300"
  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server
    container_name: "opub_redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  postgres_data:
    name: opub_postgres_data
  elasticsearch-data:
    driver: local
  redis-data:
    driver: local