# Generated by Django 4.0.7 on 2023-03-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_request_id', models.CharField(max_length=50)),
                ('payment_purpose', models.CharField(max_length=250)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dataset_api.datasetaccessmodelrequest')),
            ],
        ),
    ]
