# Generated by Django 4.0.7 on 2022-10-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_activity_target_group_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='browser',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
